---
  #destructive stops - will add a NetConf-based stop module to this
- name: Stop all VSRXes
  command: ${vmw.vmrun} stop {{ vm.basepath }}/{{ item.hostname }}/{{ item.hostname }}.vmx
  with_items:
  - hostname: ${router1.hostname}
  - hostname: ${router2.hostname}
  - hostname: ${router3.hostname}
  - hostname: ${router4.hostname}
  - hostname: ${router5.hostname}
  - hostname: ${router6.hostname}