---
- name: Copy basic configuration to /tftpboot 
  copy: src=packetbased.conf dest={{ tftp.dir }}/{{ item }} owner=nobody
  with_items:
    - router1.conf
    - router2.conf
    - router3.conf
    - router4.conf
    - router5.conf
    - router6.conf
  tags: autoinstallation
  sudo: yes